#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MrTMaker.Resource", IsApplication=true)]

namespace MrTMaker
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int camera = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int camera2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int IconoMr = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int MrTMaker = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05003c
			public const int Inicial = 2131034172;
			
			// aapt resource value: 0x7f05003d
			public const int NombreEquipo = 2131034173;
			
			// aapt resource value: 0x7f050003
			public const int OK = 2131034115;
			
			// aapt resource value: 0x7f050026
			public const int PerfilText1 = 2131034150;
			
			// aapt resource value: 0x7f050028
			public const int PerfilText2 = 2131034152;
			
			// aapt resource value: 0x7f05002a
			public const int PerfilText3 = 2131034154;
			
			// aapt resource value: 0x7f05002c
			public const int PerfilText4 = 2131034156;
			
			// aapt resource value: 0x7f05002e
			public const int PerfilText5 = 2131034158;
			
			// aapt resource value: 0x7f050030
			public const int PerfilText6 = 2131034160;
			
			// aapt resource value: 0x7f050036
			public const int Usuario = 2131034166;
			
			// aapt resource value: 0x7f050025
			public const int btnAbrirImagen = 2131034149;
			
			// aapt resource value: 0x7f050006
			public const int btnBuscarPersona = 2131034118;
			
			// aapt resource value: 0x7f05000f
			public const int btnEvaluar = 2131034127;
			
			// aapt resource value: 0x7f050012
			public const int btnGuardarEvaluacion = 2131034130;
			
			// aapt resource value: 0x7f050032
			public const int btnGuardarIndividuo = 2131034162;
			
			// aapt resource value: 0x7f05001a
			public const int btnLogin = 2131034138;
			
			// aapt resource value: 0x7f05003a
			public const int btnPersona = 2131034170;
			
			// aapt resource value: 0x7f05001b
			public const int btnRegistro = 2131034139;
			
			// aapt resource value: 0x7f050022
			public const int btnbuscar = 2131034146;
			
			// aapt resource value: 0x7f050021
			public const int btnequipo = 2131034145;
			
			// aapt resource value: 0x7f050020
			public const int btnperfil = 2131034144;
			
			// aapt resource value: 0x7f05002d
			public const int dpFechaNacimiento = 2131034157;
			
			// aapt resource value: 0x7f050007
			public const int frameLayout1 = 2131034119;
			
			// aapt resource value: 0x7f050024
			public const int imagaFotoPersonal = 2131034148;
			
			// aapt resource value: 0x7f050017
			public const int imageView1 = 2131034135;
			
			// aapt resource value: 0x7f050035
			public const int imageView2 = 2131034165;
			
			// aapt resource value: 0x7f05001e
			public const int imagenUsuario = 2131034142;
			
			// aapt resource value: 0x7f05000a
			public const int ivFotoIndividuo = 2131034122;
			
			// aapt resource value: 0x7f05003b
			public const int ivPersona = 2131034171;
			
			// aapt resource value: 0x7f050023
			public const int linearLayout1 = 2131034147;
			
			// aapt resource value: 0x7f050009
			public const int llContenedor = 2131034121;
			
			// aapt resource value: 0x7f050013
			public const int llContenidoEvaluacion = 2131034131;
			
			// aapt resource value: 0x7f05000e
			public const int llContenidoHabilidades = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int llEstatus = 2131034128;
			
			// aapt resource value: 0x7f050039
			public const int llResultados = 2131034169;
			
			// aapt resource value: 0x7f050033
			public const int lvContenedor = 2131034163;
			
			// aapt resource value: 0x7f05001c
			public const int myButton = 2131034140;
			
			// aapt resource value: 0x7f050005
			public const int nombrePersonaBuscar = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int nombreReal = 2131034114;
			
			// aapt resource value: 0x7f050037
			public const int pass = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int pass_c = 2131034168;
			
			// aapt resource value: 0x7f050015
			public const int sbBarraEvaluacion = 2131034133;
			
			// aapt resource value: 0x7f050000
			public const int scrollView1 = 2131034112;
			
			// aapt resource value: 0x7f05001d
			public const int settingsbutton = 2131034141;
			
			// aapt resource value: 0x7f050034
			public const int svRegistro = 2131034164;
			
			// aapt resource value: 0x7f050008
			public const int svResultados = 2131034120;
			
			// aapt resource value: 0x7f050011
			public const int textEstatus = 2131034129;
			
			// aapt resource value: 0x7f05000d
			public const int textSinImport = 2131034125;
			
			// aapt resource value: 0x7f050004
			public const int textView1 = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int textView11 = 2131034113;
			
			// aapt resource value: 0x7f05000c
			public const int tvCorreo = 2131034124;
			
			// aapt resource value: 0x7f050014
			public const int tvNombreAtri = 2131034132;
			
			// aapt resource value: 0x7f05000b
			public const int tvNombreCompleto = 2131034123;
			
			// aapt resource value: 0x7f050016
			public const int tvNumeroBarra = 2131034134;
			
			// aapt resource value: 0x7f05002b
			public const int txtApellidoMaterno = 2131034155;
			
			// aapt resource value: 0x7f050029
			public const int txtApellidoPaterno = 2131034153;
			
			// aapt resource value: 0x7f050031
			public const int txtEmail = 2131034161;
			
			// aapt resource value: 0x7f050027
			public const int txtNombreReal = 2131034151;
			
			// aapt resource value: 0x7f050019
			public const int txtPassword = 2131034137;
			
			// aapt resource value: 0x7f05002f
			public const int txtTelefono = 2131034159;
			
			// aapt resource value: 0x7f050018
			public const int txtUsuario = 2131034136;
			
			// aapt resource value: 0x7f05001f
			public const int txtnombre = 2131034143;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AtributoOpcion = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BuscarPersona = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DatosIndividio = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Estatus = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Evaluacion = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int HabilidadEvaluable = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Login = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Menu = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Perfil = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int PerfilEstatus = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Registro = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Relacion = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int viewResultados = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int VistaEquipos = 2130903054;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
