//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrTMaker.evaluacion {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IEvaluacion", Namespace="http://tempuri.org/")]
    public partial class SQL_Evaluacion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public SQL_Evaluacion() {
			this.Url = "http://192.168.43.5:8733/Design_Time_Addresses/HostWCF/ServicioWCF/evaluacion/evaluacion";
        }
        
        public SQL_Evaluacion(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IEvaluacion/searchEvaluacionByIndividuo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SQL_ClassLibrary")]
        public SQL_Evaluacion1[] searchEvaluacionByIndividuo(int id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idSpecified) {
            object[] results = this.Invoke("searchEvaluacionByIndividuo", new object[] {
                        id,
                        idSpecified});
            return ((SQL_Evaluacion1[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsearchEvaluacionByIndividuo(int id, bool idSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("searchEvaluacionByIndividuo", new object[] {
                        id,
                        idSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public SQL_Evaluacion1[] EndsearchEvaluacionByIndividuo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SQL_Evaluacion1[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IEvaluacion/createNewevaluacionInDB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void createNewevaluacionInDB([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_Evaluacion1 ev, out int createNewevaluacionInDBResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool createNewevaluacionInDBResultSpecified) {
            object[] results = this.Invoke("createNewevaluacionInDB", new object[] {
                        ev});
            createNewevaluacionInDBResult = ((int)(results[0]));
            createNewevaluacionInDBResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincreateNewevaluacionInDB(SQL_Evaluacion1 ev, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("createNewevaluacionInDB", new object[] {
                        ev}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndcreateNewevaluacionInDB(System.IAsyncResult asyncResult, out int createNewevaluacionInDBResult, out bool createNewevaluacionInDBResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            createNewevaluacionInDBResult = ((int)(results[0]));
            createNewevaluacionInDBResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IEvaluacion/updateEvaluacionInDB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void updateEvaluacionInDB([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_Evaluacion1 ev) {
            this.Invoke("updateEvaluacionInDB", new object[] {
                        ev});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginupdateEvaluacionInDB(SQL_Evaluacion1 ev, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updateEvaluacionInDB", new object[] {
                        ev}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndupdateEvaluacionInDB(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IEvaluacion/deleteEvaulacionInDB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void deleteEvaulacionInDB([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_Evaluacion1 ev) {
            this.Invoke("deleteEvaulacionInDB", new object[] {
                        ev});
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindeleteEvaulacionInDB(SQL_Evaluacion1 ev, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("deleteEvaulacionInDB", new object[] {
                        ev}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EnddeleteEvaulacionInDB(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IEvaluacion/searchEvaluacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SQL_Evaluacion1 searchEvaluacion(int examiner_id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool examiner_idSpecified, int examined_id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool examined_idSpecified) {
            object[] results = this.Invoke("searchEvaluacion", new object[] {
                        examiner_id,
                        examiner_idSpecified,
                        examined_id,
                        examined_idSpecified});
            return ((SQL_Evaluacion1)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsearchEvaluacion(int examiner_id, bool examiner_idSpecified, int examined_id, bool examined_idSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("searchEvaluacion", new object[] {
                        examiner_id,
                        examiner_idSpecified,
                        examined_id,
                        examined_idSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public SQL_Evaluacion1 EndsearchEvaluacion(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SQL_Evaluacion1)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IEvaluacion/searchEvaluacionByIndividuoAtributo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SQL_Evaluacion1 searchEvaluacionByIndividuoAtributo(int examiner_id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool examiner_idSpecified, int examined_id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool examined_idSpecified, int atr_id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool atr_idSpecified) {
            object[] results = this.Invoke("searchEvaluacionByIndividuoAtributo", new object[] {
                        examiner_id,
                        examiner_idSpecified,
                        examined_id,
                        examined_idSpecified,
                        atr_id,
                        atr_idSpecified});
            return ((SQL_Evaluacion1)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsearchEvaluacionByIndividuoAtributo(int examiner_id, bool examiner_idSpecified, int examined_id, bool examined_idSpecified, int atr_id, bool atr_idSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("searchEvaluacionByIndividuoAtributo", new object[] {
                        examiner_id,
                        examiner_idSpecified,
                        examined_id,
                        examined_idSpecified,
                        atr_id,
                        atr_idSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public SQL_Evaluacion1 EndsearchEvaluacionByIndividuoAtributo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SQL_Evaluacion1)(results[0]));
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SQL_Evaluacion", Namespace="http://schemas.datacontract.org/2004/07/SQL_ClassLibrary")]
    public partial class SQL_Evaluacion1 {
        
        /// <comentarios/>
        public int atr_id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool atr_idSpecified;
        
        /// <comentarios/>
        public int equ_id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool equ_idSpecified;
        
        /// <comentarios/>
        public System.DateTime eva_date;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eva_dateSpecified;
        
        /// <comentarios/>
        public int eva_id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eva_idSpecified;
        
        /// <comentarios/>
        public double eva_value;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eva_valueSpecified;
        
        /// <comentarios/>
        public int ind_idExamined;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ind_idExaminedSpecified;
        
        /// <comentarios/>
        public int ind_idExaminer;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ind_idExaminerSpecified;
        
        /// <comentarios/>
        public int opc_id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool opc_idSpecified;
        
        /// <comentarios/>
        public int par_id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool par_idSpecified;
        
        /// <comentarios/>
        public int rel_id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rel_idSpecified;
    }
}
