//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrTMaker.comentario {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IComentario", Namespace="http://tempuri.org/")]
    public partial class SQL_Comentario : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public SQL_Comentario() {
			this.Url = "http://192.168.43.5:8733/Design_Time_Addresses/HostWCF/ServicioWCF/comentario/comentario";
			//this.Url = "http://192.168.1.67:8733/Design_Time_Addresses/HostWCF/ServicioWCF/comentario/comentario";
        }
        
        public SQL_Comentario(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IComentario/getComentarioFromIndoviduo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SQL_ClassLibrary")]
        public SQL_Comentario1[] getComentarioFromIndoviduo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_Individuo person) {
            object[] results = this.Invoke("getComentarioFromIndoviduo", new object[] {
                        person});
            return ((SQL_Comentario1[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetComentarioFromIndoviduo(SQL_Individuo person, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getComentarioFromIndoviduo", new object[] {
                        person}, callback, asyncState);
        }
        
        /// <remarks/>
        public SQL_Comentario1[] EndgetComentarioFromIndoviduo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SQL_Comentario1[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IComentario/getComentarioToIndoviduo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SQL_ClassLibrary")]
        public SQL_Comentario1[] getComentarioToIndoviduo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_Individuo person) {
            object[] results = this.Invoke("getComentarioToIndoviduo", new object[] {
                        person});
            return ((SQL_Comentario1[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetComentarioToIndoviduo(SQL_Individuo person, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getComentarioToIndoviduo", new object[] {
                        person}, callback, asyncState);
        }
        
        /// <remarks/>
        public SQL_Comentario1[] EndgetComentarioToIndoviduo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SQL_Comentario1[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IComentario/getComentario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SQL_ClassLibrary")]
        public SQL_Comentario1[] getComentario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_Individuo sender, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_Individuo resiver) {
            object[] results = this.Invoke("getComentario", new object[] {
                        sender,
                        resiver});
            return ((SQL_Comentario1[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetComentario(SQL_Individuo sender, SQL_Individuo resiver, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getComentario", new object[] {
                        sender,
                        resiver}, callback, asyncState);
        }
        
        /// <remarks/>
        public SQL_Comentario1[] EndgetComentario(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SQL_Comentario1[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IComentario/createNewComentarioInB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void createNewComentarioInB([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_Comentario1 co, out int createNewComentarioInBResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool createNewComentarioInBResultSpecified) {
            object[] results = this.Invoke("createNewComentarioInB", new object[] {
                        co});
            createNewComentarioInBResult = ((int)(results[0]));
            createNewComentarioInBResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincreateNewComentarioInB(SQL_Comentario1 co, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("createNewComentarioInB", new object[] {
                        co}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndcreateNewComentarioInB(System.IAsyncResult asyncResult, out int createNewComentarioInBResult, out bool createNewComentarioInBResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            createNewComentarioInBResult = ((int)(results[0]));
            createNewComentarioInBResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IComentario/updateComentarioInDB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void updateComentarioInDB([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_Comentario1 co) {
            this.Invoke("updateComentarioInDB", new object[] {
                        co});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginupdateComentarioInDB(SQL_Comentario1 co, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updateComentarioInDB", new object[] {
                        co}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndupdateComentarioInDB(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IComentario/deleteComentarioInDB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void deleteComentarioInDB([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_Comentario1 co) {
            this.Invoke("deleteComentarioInDB", new object[] {
                        co});
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindeleteComentarioInDB(SQL_Comentario1 co, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("deleteComentarioInDB", new object[] {
                        co}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EnddeleteComentarioInDB(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SQL_ClassLibrary")]
    public partial class SQL_Individuo {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string direction;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string email;
        
        /// <comentarios/>
        public int id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified;
        
        /// <comentarios/>
        public int telephone;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool telephoneSpecified;
        
        /// <comentarios/>
        public int years;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool yearsSpecified;
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SQL_Comentario", Namespace="http://schemas.datacontract.org/2004/07/SQL_ClassLibrary")]
    public partial class SQL_Comentario1 {
        
        /// <comentarios/>
        public int com_id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool com_idSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string com_text;
        
        /// <comentarios/>
        public int ind_idResiver;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ind_idResiverSpecified;
        
        /// <comentarios/>
        public int ind_idSender;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ind_idSenderSpecified;
    }
}
