//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrTMaker.tipoRelacion {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ITipoRelacion", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQL_Object))]
    public partial class SQL_TipoRelacion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public SQL_TipoRelacion() {
			this.Url = "http://192.168.1.67:8733/Design_Time_Addresses/HostWCF/ServicioWCF/tipoRelacion/tipo" +
                "Relacion";
        }
        
        public SQL_TipoRelacion(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITipoRelacion/getRelationsType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SQL_ClassLibrary")]
        public SQL_TipoRelacion1[] getRelationsType() {
            object[] results = this.Invoke("getRelationsType", new object[0]);
            return ((SQL_TipoRelacion1[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetRelationsType(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getRelationsType", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public SQL_TipoRelacion1[] EndgetRelationsType(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SQL_TipoRelacion1[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITipoRelacion/addNewTipoRelacionInBD", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void addNewTipoRelacionInBD([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_TipoRelacion1 ti) {
            this.Invoke("addNewTipoRelacionInBD", new object[] {
                        ti});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginaddNewTipoRelacionInBD(SQL_TipoRelacion1 ti, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("addNewTipoRelacionInBD", new object[] {
                        ti}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndaddNewTipoRelacionInBD(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITipoRelacion/updateTipoRelacionInBD", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void updateTipoRelacionInBD([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_TipoRelacion1 ti) {
            this.Invoke("updateTipoRelacionInBD", new object[] {
                        ti});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginupdateTipoRelacionInBD(SQL_TipoRelacion1 ti, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updateTipoRelacionInBD", new object[] {
                        ti}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndupdateTipoRelacionInBD(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITipoRelacion/deleteTipoRelacionInDB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void deleteTipoRelacionInDB([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_TipoRelacion1 ti) {
            this.Invoke("deleteTipoRelacionInDB", new object[] {
                        ti});
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindeleteTipoRelacionInDB(SQL_TipoRelacion1 ti, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("deleteTipoRelacionInDB", new object[] {
                        ti}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EnddeleteTipoRelacionInDB(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SQL_TipoRelacion", Namespace="http://schemas.datacontract.org/2004/07/SQL_ClassLibrary")]
    public partial class SQL_TipoRelacion1 : SQL_Object {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tipRe_Description;
        
        /// <comentarios/>
        public int tipRe_id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipRe_idSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tipRe_type;
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SQL_TipoRelacion1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SQL_ClassLibrary")]
    public partial class SQL_Object {
    }
}
