//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrTMaker.equipo {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IEquipo", Namespace="http://tempuri.org/")]
    public partial class SQL_Equipo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public SQL_Equipo() {
			this.Url = "http://192.168.43.5:8733/Design_Time_Addresses/HostWCF/ServicioWCF/equipo/equipo";
        }
        
        public SQL_Equipo(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IEquipo/searchEquiposByName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SQL_ClassLibrary")]
        public SQL_Equipo1[] searchEquiposByName([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name) {
            object[] results = this.Invoke("searchEquiposByName", new object[] {
                        name});
            return ((SQL_Equipo1[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsearchEquiposByName(string name, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("searchEquiposByName", new object[] {
                        name}, callback, asyncState);
        }
        
        /// <remarks/>
        public SQL_Equipo1[] EndsearchEquiposByName(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SQL_Equipo1[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IEquipo/getAllEquipos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SQL_ClassLibrary")]
        public SQL_Equipo1[] getAllEquipos() {
            object[] results = this.Invoke("getAllEquipos", new object[0]);
            return ((SQL_Equipo1[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAllEquipos(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAllEquipos", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public SQL_Equipo1[] EndgetAllEquipos(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SQL_Equipo1[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IEquipo/getEquipoByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SQL_Equipo1 getEquipoByID(int id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idSpecified) {
            object[] results = this.Invoke("getEquipoByID", new object[] {
                        id,
                        idSpecified});
            return ((SQL_Equipo1)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetEquipoByID(int id, bool idSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getEquipoByID", new object[] {
                        id,
                        idSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public SQL_Equipo1 EndgetEquipoByID(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SQL_Equipo1)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IEquipo/updateEquipoInDB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void updateEquipoInDB([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_Equipo1 eq) {
            this.Invoke("updateEquipoInDB", new object[] {
                        eq});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginupdateEquipoInDB(SQL_Equipo1 eq, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updateEquipoInDB", new object[] {
                        eq}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndupdateEquipoInDB(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IEquipo/deleteEquipoInDB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void deleteEquipoInDB([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_Equipo1 eq) {
            this.Invoke("deleteEquipoInDB", new object[] {
                        eq});
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindeleteEquipoInDB(SQL_Equipo1 eq, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("deleteEquipoInDB", new object[] {
                        eq}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EnddeleteEquipoInDB(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SQL_Equipo", Namespace="http://schemas.datacontract.org/2004/07/SQL_ClassLibrary")]
    public partial class SQL_Equipo1 {
        
        /// <comentarios/>
        public System.DateTime equ_dateOfCreation;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool equ_dateOfCreationSpecified;
        
        /// <comentarios/>
        public int equ_id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool equ_idSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string equ_name;
    }
}
