#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Info_Personal.Resource", IsApplication=true)]

namespace Info_Personal
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int mr = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000b
			public const int BEditar = 2131034123;
			
			// aapt resource value: 0x7f050005
			public const int Direccion = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int Edad = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int Email = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int ImagenPerfil = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Nombre = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int TDireccion = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int TEdad = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public const int TEmail = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int TNombre = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int TTelefono = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int Telefono = 2131034119;
			
			// aapt resource value: 0x7f05000c
			public const int myButton = 2131034124;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Info = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
