//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrTMaker.usuario {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IUsuario", Namespace="http://tempuri.org/")]
    public partial class SQL_Usuario : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public SQL_Usuario() {
			this.Url = "http://192.168.1.67:8733/Design_Time_Addresses/HostWCF/ServicioWCF/usuario/usuario";
        }
        
        public SQL_Usuario(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUsuario/createNewUsuarioInDB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void createNewUsuarioInDB([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_Usuario1 user, out int createNewUsuarioInDBResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool createNewUsuarioInDBResultSpecified) {
            object[] results = this.Invoke("createNewUsuarioInDB", new object[] {
                        user});
            createNewUsuarioInDBResult = ((int)(results[0]));
            createNewUsuarioInDBResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincreateNewUsuarioInDB(SQL_Usuario1 user, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("createNewUsuarioInDB", new object[] {
                        user}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndcreateNewUsuarioInDB(System.IAsyncResult asyncResult, out int createNewUsuarioInDBResult, out bool createNewUsuarioInDBResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            createNewUsuarioInDBResult = ((int)(results[0]));
            createNewUsuarioInDBResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUsuario/deleteUsuarioInDB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void deleteUsuarioInDB([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_Usuario1 user) {
            this.Invoke("deleteUsuarioInDB", new object[] {
                        user});
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindeleteUsuarioInDB(SQL_Usuario1 user, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("deleteUsuarioInDB", new object[] {
                        user}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EnddeleteUsuarioInDB(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUsuario/updateUsuarioInDB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void updateUsuarioInDB([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_Usuario1 user) {
            this.Invoke("updateUsuarioInDB", new object[] {
                        user});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginupdateUsuarioInDB(SQL_Usuario1 user, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updateUsuarioInDB", new object[] {
                        user}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndupdateUsuarioInDB(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUsuario/userExist", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void userExist([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string _name, out bool userExistResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool userExistResultSpecified) {
            object[] results = this.Invoke("userExist", new object[] {
                        _name});
            userExistResult = ((bool)(results[0]));
            userExistResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginuserExist(string _name, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("userExist", new object[] {
                        _name}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EnduserExist(System.IAsyncResult asyncResult, out bool userExistResult, out bool userExistResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            userExistResult = ((bool)(results[0]));
            userExistResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUsuario/passwordIsCorrect", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void passwordIsCorrect([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string _password, out bool passwordIsCorrectResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool passwordIsCorrectResultSpecified) {
            object[] results = this.Invoke("passwordIsCorrect", new object[] {
                        _password});
            passwordIsCorrectResult = ((bool)(results[0]));
            passwordIsCorrectResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginpasswordIsCorrect(string _password, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("passwordIsCorrect", new object[] {
                        _password}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndpasswordIsCorrect(System.IAsyncResult asyncResult, out bool passwordIsCorrectResult, out bool passwordIsCorrectResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            passwordIsCorrectResult = ((bool)(results[0]));
            passwordIsCorrectResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUsuario/getUsuarioByName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SQL_Usuario1 getUsuarioByName([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string _name) {
            object[] results = this.Invoke("getUsuarioByName", new object[] {
                        _name});
            return ((SQL_Usuario1)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetUsuarioByName(string _name, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getUsuarioByName", new object[] {
                        _name}, callback, asyncState);
        }
        
        /// <remarks/>
        public SQL_Usuario1 EndgetUsuarioByName(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SQL_Usuario1)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUsuario/login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void login([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string _name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string _password, out bool loginResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool loginResultSpecified) {
            object[] results = this.Invoke("login", new object[] {
                        _name,
                        _password});
            loginResult = ((bool)(results[0]));
            loginResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginlogin(string _name, string _password, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("login", new object[] {
                        _name,
                        _password}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Endlogin(System.IAsyncResult asyncResult, out bool loginResult, out bool loginResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            loginResult = ((bool)(results[0]));
            loginResultSpecified = ((bool)(results[1]));
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SQL_Usuario", Namespace="http://schemas.datacontract.org/2004/07/SQL_ClassLibrary")]
    public partial class SQL_Usuario1 {
        
        /// <comentarios/>
        public int id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified;
        
        /// <comentarios/>
        public int ind_id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ind_idSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        /// <comentarios/>
        public int type;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified;
    }
}
