//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrTMaker.habilidad {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IHabilidad", Namespace="http://tempuri.org/")]
    public partial class SQL_Habilidad : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public SQL_Habilidad() {
			this.Url = "http://192.168.43.5:8733/Design_Time_Addresses/HostWCF/ServicioWCF/habilidad/habilidad";
			//this.Url = "http://192.168.1.67:8733/Design_Time_Addresses/HostWCF/ServicioWCF/habilidad/habilidad";
        }
        
        public SQL_Habilidad(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IHabilidad/getHabilidadByIndividuo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SQL_ClassLibrary")]
        public SQL_Habilidad1[] getHabilidadByIndividuo(int id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idSpecified) {
            object[] results = this.Invoke("getHabilidadByIndividuo", new object[] {
                        id,
                        idSpecified});
            return ((SQL_Habilidad1[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetHabilidadByIndividuo(int id, bool idSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getHabilidadByIndividuo", new object[] {
                        id,
                        idSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public SQL_Habilidad1[] EndgetHabilidadByIndividuo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SQL_Habilidad1[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IHabilidad/createNewHabilidadInDB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void createNewHabilidadInDB([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_Habilidad1 ha, out int createNewHabilidadInDBResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool createNewHabilidadInDBResultSpecified) {
            object[] results = this.Invoke("createNewHabilidadInDB", new object[] {
                        ha});
            createNewHabilidadInDBResult = ((int)(results[0]));
            createNewHabilidadInDBResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincreateNewHabilidadInDB(SQL_Habilidad1 ha, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("createNewHabilidadInDB", new object[] {
                        ha}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndcreateNewHabilidadInDB(System.IAsyncResult asyncResult, out int createNewHabilidadInDBResult, out bool createNewHabilidadInDBResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            createNewHabilidadInDBResult = ((int)(results[0]));
            createNewHabilidadInDBResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IHabilidad/updateHanilidadInDB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void updateHanilidadInDB([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_Habilidad1 ha) {
            this.Invoke("updateHanilidadInDB", new object[] {
                        ha});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginupdateHanilidadInDB(SQL_Habilidad1 ha, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updateHanilidadInDB", new object[] {
                        ha}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndupdateHanilidadInDB(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IHabilidad/deleteHabilidadInDB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void deleteHabilidadInDB([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_Habilidad1 ha) {
            this.Invoke("deleteHabilidadInDB", new object[] {
                        ha});
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindeleteHabilidadInDB(SQL_Habilidad1 ha, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("deleteHabilidadInDB", new object[] {
                        ha}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EnddeleteHabilidadInDB(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IHabilidad/IndividuoTieneAtributo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void IndividuoTieneAtributo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_Atributo atr, out bool IndividuoTieneAtributoResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool IndividuoTieneAtributoResultSpecified) {
            object[] results = this.Invoke("IndividuoTieneAtributo", new object[] {
                        atr});
            IndividuoTieneAtributoResult = ((bool)(results[0]));
            IndividuoTieneAtributoResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIndividuoTieneAtributo(SQL_Atributo atr, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IndividuoTieneAtributo", new object[] {
                        atr}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndIndividuoTieneAtributo(System.IAsyncResult asyncResult, out bool IndividuoTieneAtributoResult, out bool IndividuoTieneAtributoResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            IndividuoTieneAtributoResult = ((bool)(results[0]));
            IndividuoTieneAtributoResultSpecified = ((bool)(results[1]));
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SQL_Habilidad", Namespace="http://schemas.datacontract.org/2004/07/SQL_ClassLibrary")]
    public partial class SQL_Habilidad1 {
        
        /// <comentarios/>
        public int atr_id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool atr_idSpecified;
        
        /// <comentarios/>
        public float hab_FinalValue;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hab_FinalValueSpecified;
        
        /// <comentarios/>
        public int hab_id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hab_idSpecified;
        
        /// <comentarios/>
        public int ind_id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ind_idSpecified;
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SQL_ClassLibrary")]
    public partial class SQL_Atributo {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string atr_drescription;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string atr_group;
        
        /// <comentarios/>
        public int atr_id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool atr_idSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string atr_name;
    }
}
