//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrTMaker.participacionEquipo {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IParticipacionEquipo", Namespace="http://tempuri.org/")]
    public partial class SQL_ParticipacionEquipo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public SQL_ParticipacionEquipo() {
			this.Url = "http://192.168.1.67:8733/Design_Time_Addresses/HostWCF/ServicioWCF/participacionEqui" +
                "po/participacionEquipo";
        }
        
        public SQL_ParticipacionEquipo(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IParticipacionEquipo/getIndividuosFromEquipo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SQL_ClassLibrary")]
        public SQL_Individuo[] getIndividuosFromEquipo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_Equipo team) {
            object[] results = this.Invoke("getIndividuosFromEquipo", new object[] {
                        team});
            return ((SQL_Individuo[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetIndividuosFromEquipo(SQL_Equipo team, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getIndividuosFromEquipo", new object[] {
                        team}, callback, asyncState);
        }
        
        /// <remarks/>
        public SQL_Individuo[] EndgetIndividuosFromEquipo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SQL_Individuo[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IParticipacionEquipo/getParticipacionesFromEquipo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SQL_ClassLibrary")]
        public SQL_ParticipacionEquipo1[] getParticipacionesFromEquipo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_Equipo team) {
            object[] results = this.Invoke("getParticipacionesFromEquipo", new object[] {
                        team});
            return ((SQL_ParticipacionEquipo1[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetParticipacionesFromEquipo(SQL_Equipo team, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getParticipacionesFromEquipo", new object[] {
                        team}, callback, asyncState);
        }
        
        /// <remarks/>
        public SQL_ParticipacionEquipo1[] EndgetParticipacionesFromEquipo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SQL_ParticipacionEquipo1[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IParticipacionEquipo/getAllParticipaciones", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SQL_ClassLibrary")]
        public SQL_ParticipacionEquipo1[] getAllParticipaciones() {
            object[] results = this.Invoke("getAllParticipaciones", new object[0]);
            return ((SQL_ParticipacionEquipo1[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAllParticipaciones(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAllParticipaciones", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public SQL_ParticipacionEquipo1[] EndgetAllParticipaciones(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SQL_ParticipacionEquipo1[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IParticipacionEquipo/getParticipacionFromIndividuo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SQL_ClassLibrary")]
        public SQL_ParticipacionEquipo1[] getParticipacionFromIndividuo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_Individuo person) {
            object[] results = this.Invoke("getParticipacionFromIndividuo", new object[] {
                        person});
            return ((SQL_ParticipacionEquipo1[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetParticipacionFromIndividuo(SQL_Individuo person, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getParticipacionFromIndividuo", new object[] {
                        person}, callback, asyncState);
        }
        
        /// <remarks/>
        public SQL_ParticipacionEquipo1[] EndgetParticipacionFromIndividuo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SQL_ParticipacionEquipo1[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IParticipacionEquipo/createNewParticipacionInDB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void createNewParticipacionInDB([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_ParticipacionEquipo1 pa, out int createNewParticipacionInDBResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool createNewParticipacionInDBResultSpecified) {
            object[] results = this.Invoke("createNewParticipacionInDB", new object[] {
                        pa});
            createNewParticipacionInDBResult = ((int)(results[0]));
            createNewParticipacionInDBResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincreateNewParticipacionInDB(SQL_ParticipacionEquipo1 pa, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("createNewParticipacionInDB", new object[] {
                        pa}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndcreateNewParticipacionInDB(System.IAsyncResult asyncResult, out int createNewParticipacionInDBResult, out bool createNewParticipacionInDBResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            createNewParticipacionInDBResult = ((int)(results[0]));
            createNewParticipacionInDBResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IParticipacionEquipo/updateNewParticipacionInDB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void updateNewParticipacionInDB([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_ParticipacionEquipo1 pa) {
            this.Invoke("updateNewParticipacionInDB", new object[] {
                        pa});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginupdateNewParticipacionInDB(SQL_ParticipacionEquipo1 pa, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updateNewParticipacionInDB", new object[] {
                        pa}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndupdateNewParticipacionInDB(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IParticipacionEquipo/deleteParticipacionInDB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void deleteParticipacionInDB([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_ParticipacionEquipo1 pa) {
            this.Invoke("deleteParticipacionInDB", new object[] {
                        pa});
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindeleteParticipacionInDB(SQL_ParticipacionEquipo1 pa, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("deleteParticipacionInDB", new object[] {
                        pa}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EnddeleteParticipacionInDB(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SQL_ClassLibrary")]
    public partial class SQL_Equipo {
        
        /// <comentarios/>
        public System.DateTime equ_dateOfCreation;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool equ_dateOfCreationSpecified;
        
        /// <comentarios/>
        public int equ_id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool equ_idSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string equ_name;
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SQL_ParticipacionEquipo", Namespace="http://schemas.datacontract.org/2004/07/SQL_ClassLibrary")]
    public partial class SQL_ParticipacionEquipo1 {
        
        /// <comentarios/>
        public int equ_id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool equ_idSpecified;
        
        /// <comentarios/>
        public int ind_id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ind_idSpecified;
        
        /// <comentarios/>
        public System.DateTime par_dateOfJoin;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool par_dateOfJoinSpecified;
        
        /// <comentarios/>
        public int par_id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool par_idSpecified;
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SQL_ClassLibrary")]
    public partial class SQL_Individuo {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string direction;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string email;
        
        /// <comentarios/>
        public int id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified;
        
        /// <comentarios/>
        public int telephone;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool telephoneSpecified;
        
        /// <comentarios/>
        public int years;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool yearsSpecified;
    }
}
