//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrTMaker.relacion {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IRelacion", Namespace="http://tempuri.org/")]
    public partial class SQL_Relacion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public SQL_Relacion() {
			this.Url = "http://192.168.43.5:8733/Design_Time_Addresses/HostWCF/ServicioWCF/relacion/relacion";
			//this.Url = "http://192.168.1.67:8733/Design_Time_Addresses/HostWCF/ServicioWCF/relacion/relacion";
		}
        
        public SQL_Relacion(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IRelacion/getRelations", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SQL_ClassLibrary")]
        public SQL_Relacion1[] getRelations([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_Individuo person) {
            object[] results = this.Invoke("getRelations", new object[] {
                        person});
            return ((SQL_Relacion1[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetRelations(SQL_Individuo person, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getRelations", new object[] {
                        person}, callback, asyncState);
        }
        
        /// <remarks/>
        public SQL_Relacion1[] EndgetRelations(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SQL_Relacion1[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IRelacion/createNewRelacionInDB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void createNewRelacionInDB([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_Relacion1 re, out int createNewRelacionInDBResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool createNewRelacionInDBResultSpecified) {
            object[] results = this.Invoke("createNewRelacionInDB", new object[] {
                        re});
            createNewRelacionInDBResult = ((int)(results[0]));
            createNewRelacionInDBResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincreateNewRelacionInDB(SQL_Relacion1 re, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("createNewRelacionInDB", new object[] {
                        re}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndcreateNewRelacionInDB(System.IAsyncResult asyncResult, out int createNewRelacionInDBResult, out bool createNewRelacionInDBResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            createNewRelacionInDBResult = ((int)(results[0]));
            createNewRelacionInDBResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IRelacion/deleteRelacionInDB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void deleteRelacionInDB([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_Relacion1 re) {
            this.Invoke("deleteRelacionInDB", new object[] {
                        re});
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindeleteRelacionInDB(SQL_Relacion1 re, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("deleteRelacionInDB", new object[] {
                        re}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EnddeleteRelacionInDB(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IRelacion/updateRelacionInDB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void updateRelacionInDB([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SQL_Relacion1 re) {
            this.Invoke("updateRelacionInDB", new object[] {
                        re});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginupdateRelacionInDB(SQL_Relacion1 re, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("updateRelacionInDB", new object[] {
                        re}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndupdateRelacionInDB(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SQL_ClassLibrary")]
    public partial class SQL_Individuo {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string direction;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string email;
        
        /// <comentarios/>
        public int id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified;
        
        /// <comentarios/>
        public int telephone;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool telephoneSpecified;
        
        /// <comentarios/>
        public int years;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool yearsSpecified;
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SQL_Relacion", Namespace="http://schemas.datacontract.org/2004/07/SQL_ClassLibrary")]
    public partial class SQL_Relacion1 {
        
        /// <comentarios/>
        public int ind_idFin;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ind_idFinSpecified;
        
        /// <comentarios/>
        public int ind_idIni;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ind_idIniSpecified;
        
        /// <comentarios/>
        public int rel_id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rel_idSpecified;
        
        /// <comentarios/>
        public double rel_val;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rel_valSpecified;
        
        /// <comentarios/>
        public int tipRe_id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipRe_idSpecified;
    }
}
